title: Nick Danis
#logo: /assets/img/logo.png
description: Lecturer
show_downloads: false
google_analytics: 
remote_theme: ankitsultana/researcher@gem

footer: "Page design by Ankit Sultana"
footer_url: "https://github.com/ankitsultana"

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata