title: Nick Danis
author:
  name: Nick Danis 
  pronouns: he/him
  email: nsdanis@wustl.edu
description: >
  Washington University in St. Louis Linguistics Program
  
address-1: Campus Box 1073
address-2: One Brookings Drive
address-3: St. Louis, MO 63130 

show_excerpts: false # set to true to show excerpts on the homepage


# social links
# twitter_username: jekyllrb
github_username:  https://github.com/nickdanis
orcid: https://orcid.org/0000-0002-1854-0000
google_scholar: https://scholar.google.com/citations?user=wAsnRk4AAAAJ
# rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: https://www.linkedin.com/in/nickdanis/
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com


# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- research.md
- teaching.md
- posts.md
- cv.md

# Build settings
theme: minima


plugins:
 - jekyll-feed
 - jekyll-seo-tag