# personal info
url: https://www.nickdanis.com
title: Nick Danis
author:
  name: Nick Danis 
  pronouns: he/him
  email: nsdanis@wustl.edu
  ipa: nɪk ˈdænɪs
description: >
  Washington University in St. Louis
  
address-1: Campus Box 1073
address-2: One Brookings Drive
address-3: St. Louis, MO 63130 

# teaching info
current_semester: Fall 2021

collections:
  syllabi:
    output: true
    permalink: /:collection/:name
    sort-by: year
  research:
    output: true
    permalink: /:collection/:name
  wiki:
    output: false
    permalink: /:collection/:name


fa2021:
  office-hours: TBD
  office-location: January 206 / Zoom


# site info
github:  https://github.com/nickdanis
twitter: https://twitter.com/autosegment
orcid: https://orcid.org/0000-0002-1854-0000
medium: https://nickdanis.medium.com/
google_scholar: https://scholar.google.com/citations?user=wAsnRk4AAAAJ
linkedin: https://www.linkedin.com/in/nickdanis/

google_analytics: G-YBJDGB84MG

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- research.md
- teaching.md
- publications.md
- posts.md
- cv.md

permalink: pretty
show_excerpts: true # set to true to show excerpts on the homepage

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag