theme: jekyll-theme-minimal
title: Nick Danis
description: |
  Lecturer in Linguistics
  Washington University in St. Louis
  Linguistics Program
  Campus Box 1073
  One Brookings Drive
  St. Louis, MO 63130-4899
