title: Nick Danis
#logo: /assets/img/f2.jpg
description: Lecturer in Linguistics
show_downloads: false
google_analytics:
markdown: kramdown
theme: jekyll-theme-minimal
pronouns: he/him
pronunciation: "[ˈnɪk ˈdænɪs]"
email: nsdanis@wustl.edu
affiliation: Washington University in St. Louis
position: Lecturer in Linguistics